export {default as Home} from './Home.js'
export {default as Game} from './Game.js'
export {default as Start} from './Start.js'
export {default as Leaderboard} from './Leaderboard.js'
export {default as Result} from './Result.js'